language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install .
  - sudo apt-get install -y socat
script:
  - cd cosplay/tests
  - socat -d -d pty,raw,echo=0 pty,raw,echo=0 > socatout 2>&1 &
  - COSplay --port "$(head -1 socatout | cut -d ' ' -f 7)" --storage_path ~ > COSplayout 2>&1 &
  - python test_server.py "$(sed -n '2p' socatout | cut -d ' ' -f 7)"
  - cat socatout
  - cat COSplayout
