language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install .
  - sudo apt-get install -y socat
script:
  - cd cosplay/tests
  - socat -d -d pty,raw,echo=0 pty,raw,echo=0 > socatout 2>&1 &
  - X=$(head -2 socatout)
  - COSplay --port "${X:42:11}" --storage_path ~ > COSplayout 2>&1 &
  - pytest test_server.py ${X:96:11}
  - cat socatout
  - cat COSplayout
