language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install .
  - sudo apt-get install -y socat
script:
  - socat -d -d /dev/pts/2,raw,echo=0 /dev/pts/3,raw,echo=0 &
  - COSplay --port /dev/pts/2 --storage_path ~ &
  - py.test
