language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install .
  - sudo apt-get install -y socat
script:
  - socat -d -d pty,raw,echo=0 pty,raw,echo=0 &
  - COSplay --port /dev/pts/24 --storage_path ~
  - py.test
