#!/bin/bash

a=95
while ! [[ -e  "/etc/udev/rules.d/$a-pyboard.rules" ]]
do
a=$(( $a-1 ))
done

[[ $a ]] || {
	echo 'Could not find rules generated with grant_permissions_for_pyboard script.'
	exit 1
}

md5=($(md5sum /etc/udev/rules.d/$a-pyboard.rules))


if [[ $md5 = fd90722a95c228ef23d20909a3fb7495 ]]
then
sudo rm -f /etc/udev/rules.d/$a-pyboard.rules
echo "/etc/udev/rules.d/$a-pyboard.rules was removed."
else
echo $'\n\n'
echo "md5sum miss match! File was probably altered manually. Make sure there are no rules not related to the pyboard in /etc/udev/rules.d/$a-pyboard.rules and delete it manually."
echo $'\n\n'
echo "Lines added by the grant_permissions look as follows:"
echo "# f055:9800, 9801, 9802 MicroPython pyboard
ATTRS{idVendor}=="f055", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="f055", ENV{MTP_NO_PROBE}="1"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="f055", MODE="0666"
KERNELS=="ttyACM*", ATTRS{idVendor}=="f055", MODE="0666"
SYSFS{idVendor}=="f055", ENV{ID_MM_DEVICE_IGNORE}="1"
SYSFS{idVendor}=="f055", ENV{MTP_NO_PROBE}="1"
SUBSYSTEMS=="usb", SYSFS{idVendor}=="f055", MODE="0666"
KERNELS=="ttyACM*", SYSFS{idVendor}=="f055", MODE="0666"
"
exit 1
fi

sudo udevadm control --reload-rules 1> /dev/null 2>&1 || sudo udevcontrol reload_rules ||{
echo "Could not reload rules."; exit 1 }

echo "udev rules were successfully reloaded"
